[package]
name = "timberwolf-demo"
version = "0.4.0"
authors = ["Alexander Barber <alex@dangerzonegames.com>"]
edition = "2018"

[dependencies]
timberwolf = { version="*", path="../" }
winit = "0.19.5"
